- name: Create snapshots for specified VMs
  hosts: all
  gather_facts: no
  vars:
    snapshot_name: "Ansible-Snapshot-1" # Define the snapshot name here

  tasks:
  - name: Include VM names from a separate file
    include_vars:
      file: 2012_vm_names.yml # Change the file name as needed

  - name: Check if snapshot with given name already exists for each VM
    community.vmware.vmware_guest_snapshot_info:
      validate_certs: no
      vm_id: "{{ item }}"
    register: snapshot_info
    with_items: "{{ vm_names }}"

  - name: Create snapshot for each VM if it doesn't already exist
    community.vmware.vmware_guest_snapshot:
      validate_certs: no
      vm_id: "{{ item }}"
      name: "{{ snapshot_name }}"
      description: "Snapshot created by Ansible"
      memory: no
      quiesce: no
    when: "'{{ snapshot_name }}' not in snapshot_info.snapshots | map(attribute='name') | list"
    with_items: "{{ vm_names }}"
