---
- name: Check system requirements and disk space for Windows Server upgrade
  hosts: all
  gather_facts: no

  tasks:
    - name: Check installed RAM
      win_shell: 'Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty TotalPhysicalMemory'
      register: total_ram

    - name: Check CPU count
      win_shell: 'Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty NumberOfProcessors'
      register: cpu_count

    - name: Ensure at least 2 CPUs are available
      fail:
        msg: "At least 2 CPUs are required for the upgrade."
      when: cpu_count.stdout|int < 2

    - name: Check free disk space on C
      win_shell: '(Get-PSDrive C).Free'
      register: disk_space

    - name: Display system requirements
      debug:
        msg:
          - "Total RAM: {{ total_ram.stdout|int // (1024*1024*1024) }} GB"
          - "CPU Count: {{ cpu_count.stdout }}"
          - "Disk Space Information: {{ disk_space.stdout }}"

    - name: Ensure at least 32GB of free disk space is available on C
      fail:
        msg: "At least 32GB of free disk space is required for the upgrade."
      when: disk_space.stdout|int < 34359738368  # 32GB in bytes

    - name: Check disk space
      win_command: powershell.exe -Command "Get-PSDrive C"
      register: disk_check

    - name: Display disk space
      debug:
        msg: "Disk space: {{ disk_check.stdout }}"
