---
- name: Directory Check
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure directory exists for download
      win_file:
        path: C:\temp
        state: directory
        force: yes